name: RK2
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  jobs:
    building_job:
      runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2
          
          - name: Install CMake
            run : |
              sudo apt-get update
              sudo apt-get install -y cmake

          - name: Build with CMake
            run: |
              mkdir -p build
              cd build
              cmake ..
              build
          - name: Upload artifact
            uses: actions/upload-artifact@v2
            with:
              name: myapp
              path: build/myapp
          
      
