name: RK2
on:
  push:
    branches:
    - master
    - release/*
  pull_request:
    branches:
    - master
  jobs:
    building_job:
      runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
          
      
